# +-------------+
# | Minecaching |
# |    Config   |
# +-------------+

# Do not touch!
CONFIG_VERSION: 11
MINECACHE_DATA_VERSION: 6
PLAYER_DATA_VERSION: 6
LOGBOOK_DATA_VERSION: 1

# Determines the Locale to use for plugin messages
# Currently supports: en-US
# Defaults: en-US
LOCALE: en-US

# Determines whether the plugin will automatically update
# Defaults: false
AUTO_UPDATE: false
# Determines the branch to use for the auto updater
# release: Release versions, such as 0.2.2.1, 0.2.2.2, 0.2.2.3
# snapshot: Snapshot versions, such as 0.2.2.3-SNAPSHOT-1, 0.2.2.3, 0.4.0.0-snapshot-24w14a
# Defaults: release
UPDATE_BRANCH: release
# Determines whether experimental features are enabled
# Defaults: false
EXPERIMENTAL_FEATURES: false
# Determines whether or not event messages are logged
# Defaults: false
DEBUG_EVENTS: false
# Defines the amount of information being outputted
# 0 provides a basic overview of the event
# 1 provides the basic overview along with the most important event data
# 2 provides the basic overview along with all event data
# Defaults: 0
DEBUG_EVENTS_LEVEL: 0

# Determines the boundaries for where a Minecache can be placed in the Y direction
# Only recommended to change this if you have custom terrain generation or have differing world heights from vanilla
# Defaults: 319 for Max, -64 for Min.
MAX_Y: 319
MIN_Y: -64

# Determines the boundaries for where a Minecache can be placed in the XZ plane
# Only recommended to change this if you have custom terrain generation or have differing world heights from vanilla
# Defaults: 30000000 for Max, -30000000 for Min.
MAX_X: 30000000
MIN_X: -30000000
MAX_Z: 30000000
MIN_Z: -30000000

# Determines the minimum amount of separation between caches in blocks
# Defaults: 25
MIN_CACHE_DISTANCE: 25

# Determines the maximum distance a cache lodestone can be from the cache
# Defaults: 50
MAX_LODESTONE_DISTANCE: 50
# Determines how far away from a cache lodestone the compass will be removed
# Defaults: 25
FIND_LODESTONE_DISTANCE: 25
# Determines whether to use lodestone-based locating or coordinate-based locating
# Coordinate-based is stable, it tells the player the rough coordinates of the cache
# Lodestone-based is stable until more than one player is locating the same cache. This may be fixed in the future
# Defaults: false (Coordinate-based)
USE_LODESTONE_BASED_LOCATING: false

# Determines how long the wait between placing caches is (in seconds). Set to 0 to disable.
# Default: 300 (5 minutes)
CACHE_CREATE_COOLDOWN: 300

# Determines which types are enabled on the server
# Available Types: traditional, mystery, multi
ENABLED_TYPES:
  - traditional
  - mystery
  - multi

# Defines how the 'score' is calculated for the Most Accomplished stat.
# FIND is how many points for you get for finding a cache
# FAVORITE is how many points for getting a favorite point on one of your caches
# FTF is how many points for getting an FTF on a cache
# HIDE_X is how many points for having a hide with the type X:
#   AD is archived/disabled, R is reviewing, NM is needs maintenance, and P is published. All others types default to 0
# Defaults:
#   FIND: 1
#   FAVORITE: 1
#   FTF: 10
#   HIDE_AD: 0
#   HIDE_R: 2
#   HIDE_NM: 3
#   HIDE_P: 5
STATS_SCORE_OPTIONS:
  FIND: 1
  FAVORITE: 1
  FTF: 10
  HIDE_AD: 0
  HIDE_R: 2
  HIDE_NM: 3
  HIDE_P: 5